- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/styles.scss
Added more styles to the header
> Added more styles to the header

- src/app/shared/menu/menu.component.scss
added media queries for the menu list
> added media queries for the menu list

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/bot-config-feature/bot-config.module.ts
- src/app/header/header.component.ts
- src/app/shared/shared.module.ts
- src/app/shared/shared.service.spec.ts
- src/app/shared/shared.service.ts
Updated to include a shared service
> Updated to include a shared service

- src/app/bot-config-feature/bot-config-routing.module.ts
- src/app/bot-config-feature/bot-config.module.ts
- src/app/bot-config-feature/topic-config/topic-config.component.html
- src/app/bot-config-feature/topic-config/topic-config.component.ts
- src/app/bot-config-feature/topic-questions/topic-questions.component.html
- src/app/bot-config-feature/topic-questions/topic-questions.component.spec.ts
- src/app/bot-config-feature/topic-questions/topic-questions.component.ts
Configured the Topic Questions screen
> Added the topic Questions compoment

- src/app/bot-config-feature/topic-config/topic-questions/topic-questions.component.html
> updated the image name

- src/app/bot-config-feature/topic-config/topic-answers/topic-answers-slider/topic-answers-slider.component.html
- src/app/bot-config-feature/topic-config/topic-answers/topic-answers-slider/topic-answers-slider.component.ts
updated to remove arrow on the last answer
> updated to remove arrow on the last answer

- src/app/bot-config-feature/topic-config/topic-answers/topic-response-button/topic-response-button.component.html
- src/app/bot-config-feature/topic-config/topic-answers/topic-response-text/topic-response-text.component.html
Changes for saving the radio response
> Changes for saving the radio response

- src/app/bot-config-feature/bot-config-routing.module.ts
- src/app/bot-config-feature/bot-config.module.ts
- src/app/bot-config-feature/bot-name/bot-name.component.html
- src/app/bot-config-feature/build-the-bot/build-the-bot.component.html
- src/app/bot-config-feature/build-the-bot/build-the-bot.component.spec.ts
- src/app/bot-config-feature/build-the-bot/build-the-bot.component.ts
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.html
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.spec.ts
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.ts
- src/app/bot-config-feature/topic-config/topic-config.component.html
- src/app/constants/menu.constants.ts
Added new files for building the bot
> Added new files for building the bot

- src/app/bot-config-feature/bot-config/bot-config.component.ts
added unsubscribe to ngDestroy
> added unsubscribe to ngDestroy

- src/app/bot-config-feature/bot-name/bot-name.component.html
- src/app/bot-config-feature/bot-name/bot-name.component.ts
- src/app/bot-config-feature/build-the-bot/build-the-bot.component.html
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.html
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.ts
- src/app/bot-config-feature/topic-config/topic-config.component.html
- src/app/bot-config-feature/topic-config/topic-config.component.ts
- src/index.html
- src/styles.scss
> updated the chat simulator

- src/app/bot-config-feature/bot-config.service.ts
> button template

- src/app/bot-config-feature/build-the-bot/build-the-bot.component.html
- src/index.html
- src/styles.scss
changes for making the app work in the server
> changes for making the app work in the server

- src/app/app.service.ts
- src/app/bot-config-feature/bot-config.service.ts
- src/app/bot-config-feature/topic-config/topic-slider/topic-slider.component.html
- src/app/bot-config-feature/topic-config/topic-slider/topic-slider.component.scss
- src/app/shared/menu/menu.component.scss
changed the end point to server end point and css changes
> changed the end point to server end point and css changes

- src/app/app.service.ts
- src/app/bot-config-feature/bot-config.service.ts
- src/app/bot-config-feature/topic-config/topic-answers/buttons/buttons.component.ts
- src/app/shared/model/topic/button.model.ts
> Updated the end point

- src/app/bot-config-feature/bot-config.service.ts
- src/app/shared/model/topic/kyc/payload.model.ts
> generic template

- src/app/app.component.html
- src/app/bot-config-feature/bot-header/bot-header.component.ts
- src/app/shared/loading-screen/loading-screen.component.html
- src/app/shared/loading-screen/loading-screen.component.scss
- src/app/shared/loading-screen/loading-screen.component.spec.ts
- src/app/shared/loading-screen/loading-screen.component.ts
- src/app/shared/services/loading-screen.service.spec.ts
- src/app/shared/services/loading-screen.service.ts
- src/app/shared/shared.module.ts
added loader component and service
> added loader component and service

- src/app/bot-config-feature/topic-config/topic-answers/topic-response-element/topic-response-element.component.ts
- src/app/shared/pagination/pagination.component.ts
> updated to build the bot

- src/app/bot-config-feature/chat-simulator/chat-simulator.component.html
- src/styles.scss
> updated for chat text styling

- src/app/bot-config-feature/chat-simulator/chat-simulator.component.html
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.scss
- src/app/bot-config-feature/chat-simulator/chat-simulator.component.ts
Button styling for chat simulator
> Button styling for chat simulator

- src/app/bot-config-feature/topic-config/topic-slider/topic-slider.component.html
> style changes

- src/app/bot-config-feature/topic-config/topic-config.component.html
- src/app/bot-config-feature/topic-config/topic-config.component.ts
- src/app/bot-config-feature/topic-config/topic-config.service.ts
- src/app/bot-config-feature/topic-config/topic-name/topic-name.component.html
- src/app/bot-config-feature/topic-config/topic-name/topic-name.component.ts
- src/app/bot-config-feature/topic-config/topic-slider/topic-slider.component.html
- src/app/bot-config-feature/topic-config/topic-slider/topic-slider.component.ts
added functionality for topics to edit name
> Topic Name Edit

- src/app/bot-config-feature/bot-header/bot-header.component.ts
> Handled to add errors
